name: Deploy UiPath Package to Orchestrator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Deploy the existing .nupkg package using UiPath-Deploy
      - name: UiPath Deploy
        uses: Mikael-RnD/UiPath-Deploy@v1
        with:
          packagesPath: ${{ github.workspace }}/JDELubricantOrderEntry.1.0.8348.nupkg
          orchestratorTenant: default
          orchestratorFolder: "Shared"
          orchestratorApplicationId: ${{ secrets.UI_ORCHESTRATOR_CLIENT_ID }}
          orchestratorApplicationSecret: ${{ secrets.UI_ORCHESTRATOR_CLIENT_SECRET }}
          orchestratorLogicalName: ${{ secrets.UI_ORCHESTRATOR_INSTANCE_URL }}
