name: Deploy UiPath Package to Orchestrator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Download and Install UiPath CLI via the provided link (23.10 Version)
      - name: Download and Install UiPath CLI (23.10 Version)
        run: |
          # Download the UiPath CLI 23.10 version
          Invoke-WebRequest -Uri "https://pkgs.dev.azure.com/uipath/Public.Feeds/_apis/packaging/feeds/UiPath-Official/nuget/packages/UiPath.CLI/versions/23.10.8894.39673/content" -OutFile "UiPath.CLI.nupkg"
          
          # Create a directory for the extracted files
          New-Item -Path "uipath-cli" -ItemType Directory
          
          # Extract the NuGet package
          Expand-Archive -Path "UiPath.CLI.nupkg" -DestinationPath "uipath-cli"
          
          # Add the CLI to PATH (assuming the executable will be in the tools folder)
          $Env:Path += ";$PWD\uipath-cli\tools"

      # Step 3: Deploy the existing .nupkg package using UiPath CLI and OAuth2 (without account name)
      - name: UiPath Deploy
        run: |
          ./uipath-cli/tools/uipcli.exe package deploy "./JDELubricantOrderEntry.1.0.8348.nupkg" ${{ secrets.UI_ORCHESTRATOR_INSTANCE_URL }} default -t ${{ secrets.UI_ORCHESTRATOR_REFRESH_TOKEN }} -I ${{ secrets.UI_ORCHESTRATOR_CLIENT_ID }} -S ${{ secrets.UI_ORCHESTRATOR_CLIENT_SECRET }} --applicationScope "OR.Folders.Read OR.Settings.Read"
        env:
          UI_ORCHESTRATOR_INSTANCE_URL: ${{ secrets.UI_ORCHESTRATOR_INSTANCE_URL }}
          UI_ORCHESTRATOR_REFRESH_TOKEN: ${{ secrets.UI_ORCHESTRATOR_REFRESH_TOKEN }}
          UI_ORCHESTRATOR_CLIENT_ID: ${{ secrets.UI_ORCHESTRATOR_CLIENT_ID }}
          UI_ORCHESTRATOR_CLIENT_SECRET: ${{ secrets.UI_ORCHESTRATOR_CLIENT_SECRET }}
