name: Deploy UiPath Package to Orchestrator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Generate OAuth2 Token using the provided `curl` format
      - name: Generate OAuth2 Token
        id: generate_token
        run: |
          response=$(curl -X POST "https://z-www-orchestrator-t02.azurewebsites.net/api/Account/Authenticate" \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
            "tenancyName": "${{ secrets.UI_ORCHESTRATOR_TENANCY_NAME }}",
            "usernameOrEmailAddress": "${{ secrets.UI_ORCHESTRATOR_USERNAME }}",
            "password": "${{ secrets.UI_ORCHESTRATOR_PASSWORD }}"
          }')
          echo "::set-output name=token::$(echo $response | jq -r '.result')"

      # Step 3: Download and Install UiPath CLI via the provided link (23.10 Version)
      - name: Download and Install UiPath CLI (23.10 Version)
        run: |
          # Download the UiPath CLI 23.10 version
          Invoke-WebRequest -Uri "https://pkgs.dev.azure.com/uipath/Public.Feeds/_apis/packaging/feeds/UiPath-Official/nuget/packages/UiPath.CLI/versions/23.10.8894.39673/content" -OutFile "UiPath.CLI.nupkg"
          
          # Create a directory for the extracted files
          New-Item -Path "uipath-cli" -ItemType Directory
          
          # Extract the NuGet package
          Expand-Archive -Path "UiPath.CLI.nupkg" -DestinationPath "uipath-cli"
          
          # Add the CLI to PATH (assuming the executable will be in the tools folder)
          $Env:Path += ";$PWD\uipath-cli\tools"

      # Step 4: Deploy the existing .nupkg package using UiPath CLI with generated token
      - name: UiPath Deploy
        run: |
          ./uipath-cli/tools/uipcli.exe package deploy "./JDELubricantOrderEntry.1.0.8348.nupkg" ${{ secrets.UI_ORCHESTRATOR_INSTANCE_URL }} default -t ${{ steps.generate_token.outputs.token }} --applicationScope "OR.Folders.Read OR.Settings.Read"
        env:
          UI_ORCHESTRATOR_INSTANCE_URL: ${{ secrets.UI_ORCHESTRATOR_INSTANCE_URL }}
