name: Deploy UiPath Package to On-Prem Orchestrator (2021.10)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Install UiPath CLI via NuGet
      - name: Install UiPath CLI
        run: |
          # Install NuGet and add it to the path
          Invoke-WebRequest -Uri "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile "nuget.exe"
          
          # Install UiPath CLI from the official NuGet feed
          ./nuget.exe install UiPath.CLI -Version 21.10.8319.10920 -OutputDirectory "uipath-cli"
          
          # Add the CLI to PATH
          $Env:Path += ";$PWD\uipath-cli\UiPath.CLI.21.10.8319.10920\tools"

      # Step 3: Authenticate with UiPath Orchestrator
      - name: Authenticate with UiPath Orchestrator
        run: |
          uipcli login -client_id $env:UI_ORCHESTRATOR_CLIENT_ID -client_secret $env:UI_ORCHESTRATOR_CLIENT_SECRET -o $env:UI_ORCHESTRATOR_INSTANCE_URL
        env:
          UI_ORCHESTRATOR_CLIENT_ID: ${{ secrets.UI_ORCHESTRATOR_CLIENT_ID }}
          UI_ORCHESTRATOR_CLIENT_SECRET: ${{ secrets.UI_ORCHESTRATOR_CLIENT_SECRET }}
          UI_ORCHESTRATOR_INSTANCE_URL: ${{ secrets.UI_ORCHESTRATOR_INSTANCE_URL }}

      # Step 4: Pack the UiPath project into a .nupkg package
      - name: Pack UiPath Project
        run: |
          uipcli pack ./UiPathProject -o "./output/uipath-package.nupkg"

      # Step 5: Push the packaged project to UiPath Orchestrator
      - name: Push UiPath Package to Orchestrator
        run: |
          uipcli push "./output/uipath-package.nupkg"
