name: Deploy UiPath Package to On-Prem Orchestrator (2021.10) with External Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Download and Install UiPath CLI from the NuGet package
      - name: Download and Install UiPath CLI
        run: |
          # Download the UiPath CLI NuGet package
          Invoke-WebRequest -Uri "https://pkgs.dev.azure.com/uipath/Public.Feeds/_apis/packaging/feeds/UiPath-Official/nuget/packages/UiPath.CLI/versions/23.10.8894.39673/content" -OutFile "UiPath.CLI.nupkg"
          
          # Create a directory for the extracted files
          New-Item -Path "uipath-cli" -ItemType Directory
          
          # Extract the NuGet package (.nupkg is essentially a zip file)
          Expand-Archive -Path "UiPath.CLI.nupkg" -DestinationPath "uipath-cli"
          
          # List contents to verify extraction
          Get-ChildItem -Path "uipath-cli"

      # Step 3: Authenticate with UiPath Orchestrator using the full path to uipcli
      - name: Authenticate with UiPath Orchestrator
        run: |
          ./uipath-cli/tools/uipcli.exe login -client_id $env:UI_ORCHESTRATOR_CLIENT_ID -client_secret $env:UI_ORCHESTRATOR_CLIENT_SECRET -o $env:UI_ORCHESTRATOR_INSTANCE_URL
        env:
          UI_ORCHESTRATOR_CLIENT_ID: ${{ secrets.UI_ORCHESTRATOR_CLIENT_ID }}
          UI_ORCHESTRATOR_CLIENT_SECRET: ${{ secrets.UI_ORCHESTRATOR_CLIENT_SECRET }}
          UI_ORCHESTRATOR_INSTANCE_URL: ${{ secrets.UI_ORCHESTRATOR_INSTANCE_URL }}

      # Step 4: Pack the UiPath project into a .nupkg package
      - name: Pack UiPath Project
        run: |
          ./uipath-cli/tools/uipcli.exe pack ./UiPathProject -o "./output/uipath-package.nupkg"

      # Step 5: Push the packaged project to UiPath Orchestrator
      - name: Push UiPath Package to Orchestrator
        run: |
          ./uipath-cli/tools/uipcli.exe push "./output/uipath-package.nupkg"
