name: Deploy UiPath Package to On-Prem Orchestrator (2021.10)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Download and Install UiPath CLI (2021 Version)
      - name: Download and Install UiPath CLI (2021 Version)
        run: |
          # Download the UiPath CLI 2021.10 version
          Invoke-WebRequest -Uri "https://pkgs.dev.azure.com/uipath/Public.Feeds/_apis/packaging/feeds/UiPath-Official/nuget/packages/UiPath.CLI/versions/21.10.8319.10920/content" -OutFile "UiPath.CLI.nupkg"
          
          # Create a directory for the extracted files
          New-Item -Path "uipath-cli" -ItemType Directory
          
          # Extract the NuGet package
          Expand-Archive -Path "UiPath.CLI.nupkg" -DestinationPath "uipath-cli"
          
          # List contents of the extracted directory to verify the structure
          Get-ChildItem -Path "uipath-cli" -Recurse

      # Step 3: Use the correct path to execute the CLI
      # This assumes that after extraction, the file is located in `tools/uipcli.exe`
      - name: Authenticate with UiPath Orchestrator
        run: |
          ./uipath-cli/tools/uipcli.exe login -client_id $env:UI_ORCHESTRATOR_CLIENT_ID -client_secret $env:UI_ORCHESTRATOR_CLIENT_SECRET -o $env:UI_ORCHESTRATOR_INSTANCE_URL
        env:
          UI_ORCHESTRATOR_CLIENT_ID: ${{ secrets.UI_ORCHESTRATOR_CLIENT_ID }}
          UI_ORCHESTRATOR_CLIENT_SECRET: ${{ secrets.UI_ORCHESTRATOR_CLIENT_SECRET }}
          UI_ORCHESTRATOR_INSTANCE_URL: ${{ secrets.UI_ORCHESTRATOR_INSTANCE_URL }}

      # Step 4: Pack the UiPath project into a .nupkg package
      - name: Pack UiPath Project
        run: |
          ./uipath-cli/tools/uipcli.exe pack ./UiPathProject -o "./output/uipath-package.nupkg"

      # Step 5: Push the packaged project to UiPath Orchestrator
      - name: Push UiPath Package to Orchestrator
        run: |
          ./uipath-cli/tools/uipcli.exe push "./output/uipath-package.nupkg"
